### ISSUE TITLE
领取 token 时 报错

### ISSUE THREAD

**Issue by leermao** [blocklet/ocap-playground#113]
![image](https://user-images.githubusercontent.com/11629887/145804014-a7029ebb-705c-4b41-9b24-6be6ceb33fb7.png)

**Comment by leermao** [comment]
![image](https://user-images.githubusercontent.com/11629887/145804163-6635c1a2-3780-430d-8584-851d5af5db06.png)

**Comment by wangshijun** [comment]
beta 链的 bug，已经 fix
