### ISSUE TITLE
Skip Hash 用例报错

### ISSUE THREAD

**Issue by polunzh** [blocklet/ocap-playground#115]
![image](https://user-images.githubusercontent.com/4244426/146515430-7d6a32ed-fbf9-45cc-8676-722c8ce02b4e.png)

![image](https://user-images.githubusercontent.com/4244426/146515442-41ab0aa7-aad3-4d3b-a0a4-d57e38602f6b.png)

**Comment by polunzh** [comment]
relates: https://github.com/ArcBlock/arc-wallet-android/issues/1828

**Comment by NateRobinson** [comment]
这个会报和 https://github.com/blocklet/ocap-playground/issues/145#issuecomment-1144472588 一样的错误

**Comment by NateRobinson** [comment]
这个 issue 应该不存在了，使用最新的 Android 钱包不会出现问题了
