### ISSUE TITLE
login 后页面报错

### ISSUE THREAD

**Issue by donotlb** [blocklet/ocap-playground#121]
报错信息如下

> ![image](https://user-images.githubusercontent.com/24994263/147637595-cedd6d1b-4195-4184-9366-1f0e3a8ef03c.png)

> ![image](https://user-images.githubusercontent.com/24994263/147637589-9daf9f82-ec17-4751-ba91-f921a116c6cf.png)

---

看了下貌似是这里的 token 为空的原因

https://github.com/blocklet/ocap-playground/blob/8f242e0677d3496ba1680b72c7d145374f79ea82/src/pages/full.js#L27-L29

![image](https://user-images.githubusercontent.com/24994263/147637683-a0e0b7e1-d11d-48a9-bb25-9374b0ff6173.png)

**Comment by wangshijun** [comment]
@donotlb api 报错了么？

**Comment by donotlb** [comment]
没报错，响应码都是 200，但请求了 2 个 session 接口

- https://playground.staging.arcblock.io/.service/@abtnode/auth-service/api/did/session
- https://playground.staging.arcblock.io/api/did/session

第 2 个响应数据是空的

**Comment by donotlb** [comment]
像是从 session 里拿的 token 为空的原因

![image](https://user-images.githubusercontent.com/24994263/147638235-60202b35-4af6-4e9f-aee8-4576c140ee6e.png)

**Comment by donotlb** [comment]
本地 blocklet dev 启动的 playground 可以正常使用

**Comment by donotlb** [comment]
已恢复正常
