### ISSUE TITLE
"Buy Token Input Test NFT" 用例出错

### ISSUE THREAD

**Issue by polunzh** [blocklet/ocap-playground#143]
![image](https://user-images.githubusercontent.com/4244426/156729891-c193e040-3b80-44a8-944c-9812f6c75128.png)

![image](https://user-images.githubusercontent.com/4244426/156729903-59978448-94dd-445f-82d5-528a02f9748f.png)

**Comment by polunzh** [comment]
https://github.com/ArcBlock/arc-wallet-android/issues/2159

**Comment by wangshijun** [comment]
fixed in latest staging
