### ISSUE TITLE
Create DID 用例出错

### ISSUE THREAD

**Issue by polunzh** [blocklet/ocap-playground#145]
![image](https://user-images.githubusercontent.com/4244426/157198541-d13d5a1b-49f4-4740-b523-141291f14655.png)

**Comment by leermao** [comment]
create new DID 报错
确信已经使用新的钱包登录过

![image](https://user-images.githubusercontent.com/11629887/164358293-14472794-ca67-42c6-8186-fdba6f065c3e.png)

**Comment by wangshijun** [comment]
把测试用例更新下，现在钱包已经不会主动 declare，更新的变更为：

去掉断言链上账户存在的逻辑

**Comment by leermao** [comment]
ok

**Comment by NateRobinson** [comment]
最新的版本会报这个错误了，应该是 DID Connect SDK 某个改动引起的。

![截屏2022-06-02 14 05 41](https://user-images.githubusercontent.com/12446758/171563796-3f68f10e-0139-4e6f-9f1b-921f8146882c.png)
