### ISSUE TITLE
DID Connect SDK 彻底移除 session 控制之后，在 playground 的应用层是否还是要有这个 session 控制

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/ocap-playground#155]
当前的 playground 必须登录才能使用，但是目前的实现我如果用 A 钱包登录之后，用 B 钱包也可以去做里面的测试用例，这个会比较让人困惑。至少能给一个提示也比较好。

**Comment by wangshijun** [comment]
fixed in latest staging
