### ISSUE TITLE
[BUG]: playground中,使用TBA购买证书时,报错 `Exchange failed: GraphQLError: Multi signature for z1bm4vrtFdz9FA4mGsNCxHhBN7raH65UVpo is not valid`

### ISSUE THREAD

**Issue by skypesky** [blocklet/ocap-playground#160]
# 1. 发生了什么?

  playground中,使用TBA购买证书时,报错 `Exchange failed: GraphQLError: Multi signature for z1bm4vrtFdz9FA4mGsNCxHhBN7raH65UVpo is not valid`

# 2. 报错截图

![67E55F5D-371F-47FC-950F-9285BDEDEF8A](https://user-images.githubusercontent.com/33124160/161966897-2b9e7462-9c7a-4dc6-b47c-a10b10ec1363.png)

![image](https://user-images.githubusercontent.com/33124160/161967286-ae7b34f7-cd89-46c5-96e0-6f15240398a8.png)

# 3. 如何复现这个错误

- step1: 访问 https://playground.staging.arcblock.io/full
- step2: 在浏览器的控制台执行代码: `localStorage.setItem("wallet_url", "https://wallet.staging.arcblock.io/")`
- step3: 点击 **Buy 1 Certificate with 1 TBA** 按钮,购买证书

**Comment by wangshijun** [comment]
fixed in latest staging
