### ISSUE TITLE
Proof Of DID Holding出问题

### ISSUE THREAD

**Issue by CreatFish** [blocklet/ocap-playground#195]
<img width="2426" alt="WeChat08fce3a2aa2865c73e9c03fdfa906d16" src="https://user-images.githubusercontent.com/15152761/186598465-282cd03b-445f-4b49-bc61-5cb9b92cdd86.png">

**Comment by CreatFish** [comment]
使用安卓 ios都报错，调试发现是target在钱包中不存在

**Comment by wangshijun** [comment]
你有 create-new-did 么？
