### ISSUE TITLE
Request NFT: Multiple Type 提示 “不是要求的VC类型”

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/ocap-playground#23]
https://github.com/ArcBlock/arc-wallet-android/issues/970

![image](https://user-images.githubusercontent.com/8749615/119124211-00083a80-ba63-11eb-9e1f-ed8e31947cd6.png)

![image](https://user-images.githubusercontent.com/8749615/119124177-f5e63c00-ba62-11eb-90f1-74cabe2e8193.png)

**Comment by wangshijun** [comment]
fixed in v0.8.9
