### ISSUE TITLE
Multiple Input Scenarios -> AcquireV3: TBA + PLAY3 付款的金额列表出现了两个 TBA

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/ocap-playground#65]
https://github.com/ArcBlock/arc-wallet-android/issues/1409

![2021-08-11-17-08-00](https://user-images.githubusercontent.com/8749615/129002124-1ec500dd-c0d4-4803-9c16-6c8e17793da2.jpg)

**Comment by wangshijun** [comment]
这应该是交易组装的问题，但是钱包端不应该展示金额为 0 的
