### ISSUE TITLE
token 平等化时 有些测试用例 broken 了

### ISSUE THREAD

**Issue by leermao** [blocklet/ocap-playground#66]
1、
![image](https://user-images.githubusercontent.com/11629887/129020343-6a6ebac1-eb1a-4d93-80a4-c76e7fe2fc35.png)

![image](https://user-images.githubusercontent.com/11629887/129020294-ace3ea2c-57e3-4f5a-b827-7528908dcfa1.png)

2、
![image](https://user-images.githubusercontent.com/11629887/129020570-c1178647-5bdd-440b-8cd7-ebb2860c78af.png)

![image](https://user-images.githubusercontent.com/11629887/129020564-79fff3b6-c617-462c-8597-9019259e448c.png)

3、
![image](https://user-images.githubusercontent.com/11629887/129020751-fff794ea-d1ff-44a0-abef-9ea20446d70b.png)

![image](https://user-images.githubusercontent.com/11629887/129020707-a9f6f995-0542-499b-9f05-9197f18985d0.png)

**Comment by wangshijun** [comment]
v0.10.3 + v0.10.4 fixed above issues
