### ISSUE TITLE
Transfer Scenarios -> Send 1 TBA + 1 Asset to Wallet 交易失败

### ISSUE THREAD

**Issue by donotlb** [blocklet/ocap-playground#68]
测试环境: https://playground.staging.arcblock.io/full  
下面两个操作都会导致交易失败

- Transfer Scenarios -> Send 1 TBA + 1 Asset to Wallet
- Transfer Scenarios -> Send 1 TBA + 1 Asset to Application

![image](https://user-images.githubusercontent.com/24994263/129675264-007e321b-36d0-4b15-9ef8-c98955a5735f.png)

**Comment by wangshijun** [comment]
fixed
