### ISSUE TITLE
文案里还是 scan QR code, 但下面实际上scan qr code只是一个选择

### ISSUE THREAD

**Issue by mave99a** [blocklet/ocap-playground#80]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/41923/131565595-483b9356-b858-4c83-8f9c-3698a6e4f285.png">

有不少这样的文案需要改进

**Comment by wangshijun** [comment]
在 node 里面的 auth service fix

**Comment by wangshijun** [comment]
https://github.com/ArcBlock/abt-node/commit/245b8fe25f6dacfdf2a4151d7640f4b375fdace9
