### ISSUE TITLE
login 和里面的按钮采用的web wallet 不同

### ISSUE THREAD

**Issue by mave99a** [blocklet/ocap-playground#98]
https://playground.staging.arcblock.io

login 和里面的按钮采用的web wallet 不同

login 用的staging, 里面的用的production

**Comment by wangshijun** [comment]
@mave99a 你在 local-storage 里面设置了自定义的 web_wallet_url 么？

**Comment by NateRobinson** [comment]
不设置 web_wallet_url 的话会复现这个问题，这个看起来像是最新的 DID Connect 组件规则不一致导致的。

Auth 的 DID Connect 组件默认的 web wallet url 指向的是 staging，但是其他的 DID Connect 组件默认的 web wallet url 是 production。

**Comment by mave99a** [comment]
建议考虑一个办法能更好地让用户选择 wallet provider

一种思路是web wallet总是到一个well known地址，然后可以选择。 另一种思路是在did connect的lib里提供。 感觉上可能前者更容易一些。 

https://github.com/blocklet/abt-wallet/issues/735

用户可能deploy自己的wallet这种做法，在abt node普及后相当可能出现

**Comment by donotlb** [comment]
看了下这个问题，DID Connect 组件有个 webWalletUrl prop，这个是需要外部传入的，如果不传默认读取 localStorage 中的 wallet_url，这块逻辑从比较早的版本开始应该一直是这样的

login 默认用的是 staging wallet，原因应该是 login 中使用 DID Connect 时，传入的 webWalletUrl 是先从 env 读取，再从 localStorage 读取，而这个 env#webWalletUrl 可以从几个地方获得 (ServiceConfig、NodeInfo  等)，试了下 playground 和 dev node [Staging 01]，不设置 localstorage 时都会默认使用 staging wallet，但我印象中以前我登录 dev node [Staging 01] 时默认用的是 production 环境的 wallet 

![image](https://user-images.githubusercontent.com/24994263/140024766-a7e3d4d1-56f0-4505-b341-edf28f9b7d2c.png)

![image](https://user-images.githubusercontent.com/24994263/140024772-c5111c91-419e-4d4b-a75f-42ac5782e46d.png)

**Comment by NateRobinson** [comment]
目前看到了多个版本的 getWalletUrl 的实现方式，建议这个方法直接封装在 lib 中，需要用到的地方引用 lib 里面的即可，避免后面逻辑再次不统一。

这个是 ocap playground 里面的 getWalletUrl 实现方式, 和 Auth 服务里面的那个不一样：
```
/* eslint-disable func-names */
export default function () {
  return window.localStorage.getItem('wallet_url') || 'https://web.abtwallet.io/';
}
```

**Comment by donotlb** [comment]
> 目前看到了多个版本的 getWalletUrl 的实现方式，建议这个方法直接封装在 lib 中，需要用到的地方引用 lib 里面的即可，避免后面逻辑再次不统一。
> 
> 这个是 ocap playground 里面的 getWalletUrl 实现方式, 和 Auth 服务里面的那个不一样：
> 
> ```
> /* eslint-disable func-names */
> export default function () {
>   return window.localStorage.getItem('wallet_url') || 'https://web.abtwallet.io/';
> }
> ```

早上也发现个 connect-demo 关于 wallet url 的问题，就是用的你贴的这段代码处理的，DID Connect 组件的 webWalletUrl prop 默认值现在是这样的：

``` js
  webWalletUrl:
    typeof window !== 'undefined' && typeof window.localStorage !== 'undefined'
      ? window.localStorage.getItem('wallet_url')
      : '',
```

是不是可以先改成 

``` js
  webWalletUrl:
    typeof window !== 'undefined' && typeof window.localStorage !== 'undefined'
      ? window.localStorage.getItem('wallet_url')
      : 'https://web.abtwallet.io/',
```

getWalletUrl 这个方法我目前只发现在使用 DID Connect 时用到了，DID Connect 改成上面这样的话，大部分 blocklet 在使用 DID Connect 组件时就不用传 webWalletUrl 了

另外 auth service 的 login，先从 env 再从 localstorage 里获取 web wallet url 是不是有别的考虑，这块需要再确认一下

**Comment by NateRobinson** [comment]
blocklet 里面还有一个地方会用到这个 web wallet url，不过如果现在的 Auth 都依赖 Auth 服务的话，是不是下面这个组件就不用再配置 wallet url 了？

```
import { SessionProvider } from '@arcblock/did-playground';
const webWalletUrl = getWebWalletUrl();

export const App = () => (
  <MuiThemeProvider theme={theme}>
    <ThemeProvider theme={theme}>
      <SessionProvider serviceHost={apiPrefix} webWalletUrl={webWalletUrl}>
        {({ session }) => {
          if (session.loading) {
            return <CircularProgress />;
          }

          if (session.user) {
            return (
              <UserProvider>
                <>
                  <CssBaseline />
                  <GlobalStyle />
                  <div className="wrapper">
                    <Switch>
                      <Route exact path="/" component={MiniPage} />
                      <Route exact path="/full" component={HomePage} />
                      <Route exact path="/profile" component={ProfilePage} />
                      <Redirect to="/" />
                    </Switch>
                  </div>
                </>
              </UserProvider>
            );
          }

          return null;
        }}
      </SessionProvider>
    </ThemeProvider>
  </MuiThemeProvider>
);
```

**Comment by donotlb** [comment]
> blocklet 里面还有一个地方会用到这个 web wallet url 

这个地方的 webWalletUrl 应该最终还是会传递给 (SessionProvider 内部的) DID Connect 组件  

https://github.com/ArcBlock/ux/blob/master/packages/did-connect/src/Session/index.js#L223

**Comment by wangshijun** [comment]
@donotlb 我看了上面的分析过程，建议改进如下：

- [ ] 把 did-connect 组件里面取 webWalletUrl 的逻辑改成和 auth-service 里面相同的逻辑，并且作为方法暴露出来
- [ ] 整体上所有组件应该还是要尊重用户自定义的 web-wallet-url，这个可以不写在 local storage 里面，而是掉用组件时直接传过来

web-wallet-url 决定的优先顺序：

- 用户自己传入的
- 从 local storage 读取的
- 从 window.env 读取的
- 默认值
